site_name: FI-BREW for FEATS
repo_url: https://github.com/Dalma-Systems/fi-brew
site_description: FEATS FI-BREW Documentation
docs_dir: docs
theme: readthedocs
pages:
  - Home: 'index.md'
  - 'User & Programmers Manual':
    - 'Architecture' : 'architecture.md'
    - 'API' : 'api.md'
  - 'Installation & Administration Manual': 
    - 'Installation Guide': 'installationguide.md'
    - 'Getting Started' : 'getting-started.md'
  - 'User Guide': 'usermanual.md'